---
name: "check lint and format"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: jurassiscripts/setup-velociraptor@v2
      - run: vr lint && vr format:check
